#
#
# $Header$
#

# Things common to both library and executable builds live in Makefile.common

# The BMSDIR variable needs to be set prior to including this file
include $(BMSDIR)/Makefile.common

.PHONY: mkdirs clean env

VPATH = $(DEP_DIR)


install: all
	mkdir -p $(JANA_BUILD_DIR)/lib
	mkdir -p $(JANA_BUILD_DIR)/include/$(MODULE_NAME)
	install -p $(LIBNAME) $(JANA_BUILD_DIR)/lib
	install -p $(wildcard *.h *.hh *.hxx) $(JANA_BUILD_DIR)/include/$(MODULE_NAME)

all: mkdirs $(DEPS) $(foreach obj,$(OBJS),$(LIBNAME)($(obj)))
	@rm -f $(DICT_FILES)
ifeq ($(BMS_OSNAME),Darwin)
	ranlib $(LIBNAME)
endif

mkdirs:
	@mkdir -p $(LIB_DIR)

clean:
	rm -rf $(LIB_DIR) $(DEP_DIR) $(DICT_FILES) *.bak *~ core  #*#

depclean: clean
	rm -rf .bin .obj .lib .depends


# Rules to make DEPENDS files from source. Note that these are similar to the
# rules in Makefile.bin, but use the implicit rules for archiving objects.
$(DEP_DIR)/%.d : %.cpp
	@mkdir -p $(DEP_DIR)
	@$(DCXX) -MM -MT "$(LIBNAME)($(notdir $(basename $@).o))" $(CXXFLAGS) $< > $@
$(DEP_DIR)/%.d : %.cc
	@mkdir -p $(DEP_DIR)
	@$(DCXX) -MM -MT "$(LIBNAME)($(notdir $(basename $@).o))" $(CXXFLAGS) $< > $@
$(DEP_DIR)/%.d : %.cxx
	@mkdir -p $(DEP_DIR)
	@$(DCXX) -MM -MT "$(LIBNAME)($(notdir $(basename $@).o))" $(CXXFLAGS) $< > $@
$(DEP_DIR)/%.d : %.c
	@mkdir -p $(DEP_DIR)
	@$(DCC) -MM -MT "$(LIBNAME)($(notdir $(basename $@).o))" $(CFLAGS) $< > $@
$(DEP_DIR)/%.d : %.F
	@mkdir -p $(DEP_DIR)
	@$(DFC) -MM -MT "$(LIBNAME)($(notdir $(basename $@).o))" $(FFLAGS) $< > $@

# Rule to make ROOT dictionary
%_Dict.cc: %.h
	rootcint -f $@ -c $(INCS) $< 


env:
	@echo FC			= $(FC)
	@echo CC			= $(CC)
	@echo CXX		= $(CXX)
	@echo FFLAGS	= $(FFLAGS)
	@echo CFLAGS	= $(CFLAGS)
	@echo CXXFLAGS	= $(CXXFLAGS)
	@echo FSRC		= $(FSRC)
	@echo CSRC		= $(CSRC)
	@echo CXXSRC	= $(CXXSRC)
	@echo LIBS		= $(LIBS)
	@echo BMS_OSNAME	= $(BMS_OSNAME)
	@echo OBJS		= $(OBJS)
	@echo MODULE_NAME   = $(MODULE_NAME)
	@echo LIBNAME	= $(LIBNAME)
	@echo DEP_DIR	= $(DEP_DIR)
	@echo DEPS		= $(DEPS)
	@echo DEPS_PATH= $(DEPS_PATH)
	@echo TMP		= $(TMP)
	@echo PACKAGES = $(PACKAGES)
	@echo PACKAGE_MAKEFILES = $(PACKAGE_MAKEFILES)
	@echo HSRC		         = $(HSRC)
	@echo BMSDIR	= $(BMSDIR)
	@echo MAKEFILE_LIST = $(MAKEFILE_LIST)

