# This defines flags which can implement (or not) features
# in a way compatible with this OS

# Use solaris compilers on SunOS
FC		= f77
CC		= cc
CXX	= CC

ifdef DEBUG
	override FFLAGS := $(filter-out -g,$(FFLAGS)) -g0
	override CFLAGS := $(filter-out -g,$(CFLAGS)) -g0
	override CXXFLAGS := $(filter-out -g,$(CXXFLAGS)) -g0
endif

CXXFLAGS += -erroff=%all

LD_SO_FLAGS = -G

MISC_LIBS += -lz -lrt -lnsl

