


all:
	make -C jana
	make -C janadump
	make -C jcalibread

install:
	make -C jana install
	make -C janadump install
	make -C jcalibread install

clean:
	make -C jana clean
	make -C janadump clean
	make -C jcalibread clean
	
