


all:
	make -C jana
	make -C janadump
	make -C jcalibread
	make -C jgeomread

install:
	make -C jana install
	make -C janadump install
	make -C jcalibread install
	make -C jgeomread install

pristine:
	make -C jana pristine
	make -C janadump pristine
	make -C jcalibread pristine
	make -C jgeomread pristine

clean:
	make -C jana clean
	make -C janadump clean
	make -C jcalibread clean
	make -C jgeomread clean
	
