


all:
	make -C jana
	make -C janadump
	make -C jcalibread
	make -C jgeomread

install:
	make -C jana install
	make -C janadump install
	make -C jcalibread install
	make -C jgeomread install

uninstall:
	make -C jana uninstall
	make -C janadump uninstall
	make -C jcalibread uninstall
	make -C jgeomread uninstall

relink:
	make -C jana relink
	make -C janadump relink
	make -C jcalibread relink
	make -C jgeomread relink

pristine:
	make -C jana pristine
	make -C janadump pristine
	make -C jcalibread pristine
	make -C jgeomread pristine

clean:
	make -C jana clean
	make -C janadump clean
	make -C jcalibread clean
	make -C jgeomread clean
	
