
import os

Import('env osname')

# Loop over libraries, building each
subdirs = ['jana', 'janadump', 'jcalibcopy', 'jcalibread', 'jgeomread', 'janactl']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

