// This file contains the content included on the main page of
// the JANA software documentaion generated by doxygen. 

/**
	\mainpage JANA Reconstruction Framework
	
	\section about About

	This documentation was generated automatically from the source
	code using the doxygen program. The content of this page is
	taken from the file doc/mainpage.c++


	\section intro Introduction

	
**/

