JANA2: JObject Class Reference
JObject Class Reference
Public Member Functions
virtual const std::string & className (void) const
void AddAssociatedObject (const JObject *obj)
void AddAssociatedObjectAutoDelete (JObject *obj, bool auto_delete=true)
void RemoveAssociatedObject (const JObject *obj)
void ClearAssociatedObjects (void)
bool IsAssociated (const JObject *locObject) const
virtual void toStrings (std::vector< std::pair< std::string, std::string > > &items) const
template<typename T >
void AddString (std::vector< std::pair< std::string, std::string > > &items, const char *name, const char *format, const T &val) const
Public Attributes
bool append_types = false
Protected Attributes
std::string mName
std::set< const JObject * > associated
std::set< JObject * > auto_delete
Member Function Documentation
void JObject::AddAssociatedObject (const JObject * obj) inline
Add a JObject to the list of associated objects
Referenced by AddAssociatedObjectAutoDelete().
void JObject::AddAssociatedObjectAutoDelete (JObject * obj, bool auto_delete = true) inline
Add a JObject to the list of associated objects. If the auto_delete flag is true, then automatically delete it when this object is deleted. Otherwise, this behaves identically to the AddAssociatedObject method.
Note that if the object is removed via RemoveAssociatedObject(...) then the object is NOT deleted. BUT, if the entire list of associated objects is cleared via ClearAssociatedObjects, then the object will be deleted.
References AddAssociatedObject().
template<typename T > void JObject::AddString (std::vector< std::pair< std::string, std::string > > & items, const char * name, const char * format, const T & val) const
Write the given value (val) to a string using the sprintf style formatting string (format) and add it to the given vector (items) with the column name "name". This is intended for use in the toStrings() method of classes that inherit from JObject.
The append_type flag provides a facility for recording the data type and value with default formatting into items. This can be used by a generic convertor (not part of JANA) to auto-generate a representation of this object for use in some other persistence package (e.g. ROOT files).
If the append_types flag is set then the data type of "val" is automatically appended with a colon (:) separator to the name (first) part of the pair. In addition, "val" is converted using stringstream and appended as well, also with a colon (:) separator. For example, if the value of name passed in is "px" and T is of type double, then the first member of the pair appended to items will be something like "px:double:1.23784" which can be decifered later to get the name, type, and value of the data member.
By default, the append_types flag is not set and the name part of the pair is a straight copy of the name argument that is passed in.
Referenced by toStrings().
void JObject::ClearAssociatedObjects (void) inline
Remove all associated objects from the associated objects list. This will also delete any objects that were added via the AddAssociatedObjectAutoDelete(...) method with the auto_delete flag set.
void JObject::RemoveAssociatedObject (const JObject * obj) inline
Remove the specified JObject from the list of associated objects. This will NOT delete the object even if the object was added with the AddAssociatedObjectAutoDelete(...) method with the auto_delete flag set.
void JObject::toStrings (std::vector< std::pair< std::string, std::string > > & items) const inline virtual
Fill the given "items" vector with items representing the (important) data members of this object. The structure of "items" is a vector of pairs. The "first" element of the pair is the name of the item as it should be displayed when dumping the item to the screen. For example, one may wish to include units using a string like "r (cm)". The "second" element of the pair is a formatted string containing the value as it should be displayed.
To facilitate this, the AddString() method exists which allows items to be added with the desired formatting using a single line.
This is a virtual method that is expected (but not required) to be implemented by all classes that inherit from JObject.
References AddString().
The documentation for this class was generated from the following files:
src/lib/JANA/JObject.h
src/lib/JANA/JObject.cc