JANA2: JApplication Class Reference
JApplication Class Reference
JANA application class (singleton).
#include <JApplication.h>
Public Types
enum RETURN_STATUS {
kSUCCESS,
kNO_MORE_EVENTS,
kTRY_AGAIN,
kUNKNOWN
}
Public Member Functions
JApplication (int narg, char *argv[])
void AddSignalHandlers (void)
int GetExitCode (void)
void Initialize (void)
void PrintFinalReport (void)
void PrintStatus (void)
void Quit (bool skip_join=false)
void Run (uint32_t nthreads=0)
void SetExitCode (int exit_code)
void SetMaxThreads (uint32_t)
void SetTicker (bool ticker_on=true)
void Stop (bool wait_until_idle=false)
void Resume (void)
void Add (JEventSourceGenerator *source_generator)
void Add (JFactoryGenerator *factory_generator)
void Add (JEventProcessor *processor)
void AddPlugin (string plugin_name)
void AddPluginPath (string path)
void GetJEventProcessors (vector< JEventProcessor * > &aProcessors)
void GetJFactoryGenerators (vector< JFactoryGenerator * > &factory_generators)
std::shared_ptr< JLogger > GetJLogger (void)
JParameterManager * GetJParameterManager (void)
JThreadManager * GetJThreadManager (void) const
JEventSourceManager * GetJEventSourceManager (void) const
std::shared_ptr< JTask< void > > GetVoidTask (void)
JFactorySet * GetFactorySet (void)
void Recycle (JFactorySet *aFactorySet)
void UpdateResourceLimits (void)
uint32_t GetCPU (void)
uint64_t GetNtasksCompleted (string name="")
uint64_t GetNeventsProcessed (void)
float GetIntegratedRate (void)
float GetInstantaneousRate (void)
void GetInstantaneousRates (vector< double > &rates_by_queue)
void GetIntegratedRates (map< string, double > &rates_by_thread)
bool IsQuitting (void)
bool IsDrainingQueues (void)
void RemoveJEventProcessor (JEventProcessor *processor)
void RemoveJFactoryGenerator (JFactoryGenerator *factory_generator)
void RemovePlugin (string &plugin_name)
string Val2StringWithPrefix (float val)
template<typename T >
T GetParameterValue (std::string name)
template<typename T >
JParameter * SetParameterValue (std::string name, T val)
Protected Member Functions
void AttachPlugins (void)
void AttachPlugin (string name, bool verbose=false)
Protected Attributes
vector< string > _args
Argument list passed in to JApplication Constructor.
int _exit_code
bool _skip_join
bool _quitting
int _verbose
bool _draining_queues
bool _ticker_on
std::chrono::time_point
< std::chrono::high_resolution_clock > mRunStartTime
std::vector< string > _plugins
std::vector< string > _plugin_paths
std::vector< void * > _sohandles
std::vector< JFactoryGenerator * > _factoryGenerators
std::vector
< JCalibrationGenerator * > _calibrationGenerators
std::vector< JEventProcessor * > _eventProcessors
std::shared_ptr< JLogger > _logger
JParameterManager * _pmanager
JEventSourceManager * _eventSourceManager
JThreadManager * _threadManager
std::size_t mNumProcessorsAdded
Detailed Description
JANA application class (singleton).
The JApplication class serves as a central access point for getting to most things in the JANA application. It owns the JThreadManager, JParameterManager, etc. It is also responsible for making sure all of the plugins are attached and other user specified configurations for the run are implemented before starting the processing of the data. User code (e.g. plugins) will generally register things like event sources and processors with the JApplication so they can be called up later at the appropriate time.
Member Function Documentation
void JApplication::Add (JEventSourceGenerator * source_generator)
Add the given JFactoryGenerator to the list of queues
Parameters
source_generator pointer to source generator to add. Ownership is passed to JApplication
void JApplication::Add (JFactoryGenerator * factory_generator)
Add the given JFactoryGenerator to the list of queues
Parameters
factory_generator pointer to factory generator to add. Ownership is passed to JApplication
void JApplication::AddPlugin (string plugin_name)
Add the specified plugin to the list of plugins to be attached. This only records the name. The plugin is not actually attached until AttachPlugins() is called (typically from Initialize() which is called from Run()). This will check if the plugin already exists in the list of plugins to attach and will not add it a second time if it is already there. This may be important if the order of plugins is important. It is left to the user to handle in those cases.
Parameters
plugin_name name of the plugin. Do not include the ".so" or ".dylib" suffix in the name. The path to the plugin will be searched from the JANA_PLUGIN_PATH envar.
void JApplication::AddPluginPath (string path)
Add a path to the directories searched for plugins. This should not include the plugin name itself. This only has an effect when called before AttachPlugins is called (i.e. before Run is called). n.b. if this is called with a path already in the list, then the call is silently ignored.
Generally, users will set the path via the JANA_PLUGIN_PATH environment variable and won't need to call this method. This may be called if it needs to be done programmatically.
Parameters
path directory to search fpr plugins.
void JApplication::AttachPlugin (string name, bool verbose = false) protected
Attach a plugin by opening the shared object file and running the InitPlugin_t(JApplication* app) global C-style routine in it. An exception will be thrown if the plugin is not successfully opened. Users will not need to call this directly since it is called automatically from Initialize().
Parameters
soname name of shared object file to attach. This may include an absolute or relative path.
verbose if set to true, failed attempts will be recorded via the JLog. Default is false so JANA can silently ignore files that are not valid plugins.
void JApplication::AttachPlugins (void) protected
Loop over list of plugin names added via AddPlugin() and actually attach and intiailize them. See AddPlugin method for more.
uint32_t JApplication::GetCPU (void)
Returns the current CPU the calling thread is running on. Note that unless the thread affinity has been set, this may change, even before returning from this call. The thread affinity of all threads may be fixed by setting the AFFINITY configuration parameter at program start up.
Referenced by JStatus::RecordBackTrace(), and JThreadManager::SetThreadAffinity().
int JApplication::GetExitCode (void)
Returns the currently set exit code. This can be used by JProcessor/JFactory classes to communicate an appropriate exit code that a jana program can return upon exit. The value can be set via the SetExitCode method.
float JApplication::GetIntegratedRate (void)
Returns the total integrated rate so far in Hz since Run was called.
JParameterManager * JApplication::GetJParameterManager (void)
Return pointer to the JParameterManager object.
Referenced by GetParameterValue(), JStatus::JStatus(), and SetParameterValue().
uint64_t JApplication::GetNeventsProcessed (void)
Return the total number of events processed.
template<typename T > T JApplication::GetParameterValue (std::string name)
This is a convenience function that just calls the method of the same name in JParameterManager.
References GetJParameterManager().
void JApplication::Initialize (void)
Initialize the application in preparation for data processing. This is called by the Run method so users will usually not need to call this directly.
void JApplication::Resume (void)
Tell all JThread objects to go into the running state (if not already there).
void JApplication::SetExitCode (int exit_code)
Set a value of the exit code in that can be later retrieved using GetExitCode. This is so the executable can return a meaningful error code if processing is stopped prematurely, but the program is able to stop gracefully without a hard exit. See also GetExitCode.
template<typename T > JParameter * JApplication::SetParameterValue (std::string name, T val)
This is a convenience function that just calls the SetParameter of JParameterManager.
References GetJParameterManager().
void JApplication::Stop (bool wait_until_idle = false)
Tell all JThread objects to go into the idle state after completing their current task. If wait_until_idle is true, this will block until all threads are in the idle state. If false (the default), it will return immediately after telling all threads to go into the idle state
void JApplication::UpdateResourceLimits (void)
Used internally by JANA to adjust the maximum size of resource pools after changing the number of threads.
string JApplication::Val2StringWithPrefix (float val)
Return the value as a string with the appropriate latin unit prefix appended. Values returned are: "G", "M", "k", "", "u", and "m" for values of "val" that are: >1.5E9, >1.5E6, >1.5E3, <1.0E-7, <1.0E-4, 1.0E-1 respectively.
The documentation for this class was generated from the following files:
src/lib/JANA/JApplication.h
src/lib/JANA/JApplication.cc