JANA2: JQueueWithBarriers Class Reference
JQueueWithBarriers Class Reference
Public Member Functions
JQueueWithBarriers (JParameterManager *aParams, const std::string &aName, std::size_t aQueueSize=200, std::size_t aTaskBufferSize=0)
JQueueWithBarriers (const JQueueWithBarriers &aQueue)
JQueueWithBarriers & operator= (const JQueueWithBarriers &aQueue)
JQueueWithBarriers (JQueueWithBarriers &&)=default
JQueueWithBarriers & operator= (JQueueWithBarriers &&)=default
Flags_t AddTask (const std::shared_ptr< JTaskBase > &aTask)
Flags_t AddTask (std::shared_ptr< JTaskBase > &&aTask)
std::shared_ptr< JTaskBase > GetTask (void)
bool AreEnoughTasksBuffered (void)
uint32_t GetMaxTasks (void)
uint32_t GetNumTasks (void)
uint64_t GetNumTasksProcessed (void)
std::size_t GetTaskBufferSize (void)
std::size_t GetLatestBarrierEventUseCount (void) const
JQueue * CloneEmpty (void) const
void FinishedWithQueue (void)
void EndThread (void)
void ThreadLoop (void)
Public Member Functions inherited from JQueue
JQueue (const std::string &aName)
JQueue (const JQueue &aQueue)=default
JQueue & operator= (const JQueue &aQueue)=default
JQueue (JQueue &&)=default
JQueue & operator= (JQueue &&)=default
virtual void AddTasksProcessedOutsideQueue (std::size_t nTasks)
virtual uint64_t GetNumTasksInserted (void)
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from JQueue
enum Flags_t {
kNone,
kQUEUE_FULL,
kNO_ERROR
}
Member Function Documentation
uint32_t JQueueWithBarriers::GetMaxTasks (void) virtual
Returns maximum number of Tasks queue can hold at one time.
Implements JQueue.
References JQueueWithLock::GetMaxTasks().
uint32_t JQueueWithBarriers::GetNumTasks (void) virtual
Returns the number of tasks currently in this queue.
Implements JQueue.
References JQueueWithLock::GetNumTasks().
uint64_t JQueueWithBarriers::GetNumTasksProcessed (void) virtual
Returns number of events that have been taken out of this queue. Does not include events still in the queue (see GetNumTasks for that).
Implements JQueue.
References JQueueWithLock::GetNumTasksProcessed().
The documentation for this class was generated from the following files:
src/lib/JANA/JQueueWithBarriers.h
src/lib/JANA/JQueueWithBarriers.cc