
import sbms

import os

Import('env osname')

# Loop over examples, building each
subdirs = ['JExample1', 'JExample2', 'JExample7', 'event_group_example']

SConscript(dirs=subdirs, exports='env osname', duplicate=0)
