#!/bin/bash
# Quick-and-dirty test cases for jana-generate.py
# Verifies that autogenerated code skeletons build with cmake and make
#
# jana-generate.py Plugin name is_standalone is_mini has_root has_tests

rm -r StandaloneNonminiRoot
jana-generate.py Plugin StandaloneNonminiRoot True False True False
cd StandaloneNonminiRoot
mkdir build
cd build
cmake .. -DROOT_DIR=/Users/nbrei/ejana_src/root/root-v6-22-02/cmake
make

cd ../..

rm -r StandaloneMiniRoot
jana-generate.py Plugin StandaloneMiniRoot True True True False
cd StandaloneMiniRoot
mkdir build
cd build
cmake .. -DROOT_DIR=/Users/nbrei/ejana_src/root/root-v6-22-02/cmake
make


cd ../..

rm -r StandaloneMiniNonroot
jana-generate.py Plugin StandaloneMiniNonroot True True False False
cd StandaloneMiniNonroot
mkdir build
cd build
cmake .. -DROOT_DIR=/Users/nbrei/ejana_src/root/root-v6-22-02/cmake
make

cd ../..

rm -r StandaloneNonminiNonroot
jana-generate.py Plugin StandaloneNonminiNonroot True False False False
cd StandaloneNonminiNonroot
mkdir build
cd build
cmake .. -DROOT_DIR=/Users/nbrei/ejana_src/root/root-v6-22-02/cmake
make

cd ../..

rm -r nonstandalones
jana-generate.py Project nonstandalones
cd nonstandalones/src/plugins

jana-generate.py Plugin Test0000 False False False False
jana-generate.py Plugin Test0010 False False True False
jana-generate.py Plugin Test0100 False True False False
jana-generate.py Plugin Test0110 False True True False

cd ../..
mkdir build
cd build
cmake .. -DROOT_DIR=/Users/nbrei/ejana_src/root/root-v6-22-02/cmake
make
cd ../src/plugins



