

all:
	make -C janadot
	make -C TestSpeed

install:
	make -C janadot install
	make -C TestSpeed install

pristine:
	make -C janadot pristine
	make -C TestSpeed pristine

clean:
	make -C janadot clean
	make -C TestSpeed clean

