
import os
import sbms

Import('env osname')

# Loop over plugins, building each
subdirs = ['TestSpeed', 'janadot', 'janactl', 'jana_iotest']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Only build janarate and janaroot if ROOTSYS is set
if os.getenv('ROOTSYS') != None :
	SConscript(dirs=['janaroot', 'janarate', 'janaview'], exports='env osname', duplicate=0)

# Optional builds
sbms.OptionallyBuild(env, ['janaevio'])

