
import sbms

import os

Import('env osname')

# Loop over plugins, building each
subdirs = ['JTest', 'JTestOld', 'janarate', 'janapy', 'zmq2jana']

SConscript(dirs=subdirs, exports='env osname', duplicate=0)
