
import sbms

import os

Import('env osname')

# Loop over libraries, building each
subdirs = ['lib', 'programs', 'plugins', 'examples']
#subdirs = ['libJANA', 'plugins', 'utilities', 'unit_tests']

#sbms.OptionallyBuild(env, ['examples'])
SConscript(dirs=subdirs, exports='env osname', duplicate=0)
