
import sbms

import os

Import('env osname')

# Loop over libraries, building each
subdirs = ['libraries', 'programs', 'plugins', 'examples']

#sbms.OptionallyBuild(env, ['examples'])
SConscript(dirs=subdirs, exports='env osname', duplicate=0)
