name: Dependency matrix tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jana2_env_everything_except_cuda:
    name: Build JANA2 with all dependencies except CUDA
    runs-on: ubuntu-latest
    container:
      image: nbrei/jana2_env_everything_except_cuda
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        # LD_LIBRARY_PATH needs to be set HERE in order to propagate to CTest now. (I don't like this!)
        # CTest needs the LD_LIBRARY_PATH set so that ROOT can find the dictionaries for Podio IO.
        # (Remember that ROOT won't use RPath for this purpose)
        export LD_LIBRARY_PATH=/app/podio/install/lib:$LD_LIBRARY_PATH
        cmake -S . -B build \
          -DCMAKE_INSTALL_PREFIX=`pwd` \
          -DUSE_PYTHON=ON \
          -DUSE_ROOT=ON \
          -DUSE_PODIO=ON \
          -DUSE_XERCES=ON \
          -DUSE_ZEROMQ=ON \
          -DXercesC_DIR=/usr \
          -Dpodio_DIR=/app/podio/install/lib/cmake/podio/
        cmake --build build --target install
    - name: Examine dynamic linking
      run: |
        echo "ldd bin/jana"
        ldd bin/jana
        echo "ldd lib/libJANA.so"
        ldd lib/libJANA.so
        echo "RPATH of bin/jana:"
        objdump -x bin/jana | grep PATH || echo "Empty!"
        echo "RPATH of lib/libJANA.so:"
        objdump -x lib/libJANA.so | grep PATH || echo "Empty!"
        echo "RPATH of lib/JANA/plugins/TimesliceExample.so:"
        objdump -x lib/JANA/plugins/TimesliceExample.so | grep PATH || echo "Empty!"
        echo "RPATH of bin/PodioExample:"
        objdump -x bin/PodioExample | grep PATH || echo "Empty!"

    - name: JTest
      run: |
        ctest --test-dir build --output-on-failure -R jana-plugin-jtest-tests
    - name: jana-unit-tests
      run: |
        ctest --test-dir build --output-on-failure -R jana-unit-tests
    - name: TimesliceExample with simple (physics event) topology
      run: |
        ctest --test-dir build --output-on-failure -R jana-example-timeslices-simple-tests
    - name: TimesliceExample with complex (timeslice) topology
      run: |
        ctest --test-dir build --output-on-failure -R jana-example-timeslices-complex-tests
    - name: Janadot
      run: |
        ctest --test-dir build --output-on-failure -R jana-plugin-janadot-tests
    - name: Other examples
      run: |
        ctest --test-dir build --output-on-failure -R "jana-example-dst-tests|jana-example-tutorial-tests|jana-example-eventgroup-tests|jana-example-unit-tests|jana-example-podio-tests"




